language: ruby
cache: bundler
rvm:
  - 2.7.4
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
notifications:
  email: false
