# Site settings
title: Walter Breakell
author: Walter Breakell
description: >
  Walter Breakell is a software engineer focused on building smart, thoughtful
  web applications.
baseurl: ""
url: "https://wbreakell.github.io"
twitter_username: wbreakell
github_username: wbreakell
dribbble_username: wbreakell

# Build settings
markdown: kramdown
permalink: /blog/:title/
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - vendor
