# Site settings
title: Walter Breakell
author: Walter Breakell
description: >
  Walter Breakell is a user experience engineer at Google, leveraging his dual
  expertise in engineering and design to build intuitive digital experiences.
baseurl: ""
url: "https://wbreakell.io"
x_username: wbreakell
mastodon_username: wbreakell
github_username: wbreakell
dribbble_username: wbreakell

# Build settings
markdown: kramdown
permalink: /blog/:title/
sass:
  style: compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - vendor
